### ISSUE TITLE
Object Literal Extensions & __proto__

### ISSUE THREAD

**Issue by Fishrock123** [lukehoban/es6features#46]
Under [enhanced object literals](https://github.com/lukehoban/es6features#enhanced-object-literals) it would look like `__proto__` wasn't available before, however, it appears to be, as I am using that functionality in node 0.10.

**Comment by mathiasbynens** [comment]
`__proto__` wasn’t in the spec before.

**Comment by Fishrock123** [comment]
Hmm, strange it landed so soon? It's not listed on kangax's charts either.

**Comment by lukehoban** [comment]
`__proto__` was a de-facto standard, implemented in many engines, but had never been officially part of the ECMAScript standard until ES6.  So it's included here as an ES6 feature, but most engines have had it for many years.

**Comment by Fishrock123** [comment]
Makes sense.
