### ISSUE TITLE
Example of 'Construct an HTTP request prefix' no clear

### ISSUE THREAD

**Issue by mieszko4** [lukehoban/es6features#49]
Example of 'Construct an HTTP request prefix' in 'Template Strings' is not clear.

The following code:
```
// Construct an HTTP request prefix is used to interpret the replacements and construction
GET`http://foo.org/bar?a=${a}&b=${b}
    Content-Type: application/json
    X-Credentials: ${credentials}
    { "foo": ${foo},
      "bar": ${bar}}`(myOnReadyStateChangeHandler);
```

is not clear to me. Is GET a function defined in ES6 spec?. How can I test it? Is there a simpler example that would show intention of this example?

**Comment by mieszko4** [comment]
I understand now what you intended to show in this example:
* String representing a GET request is tagged by 'GET' tag; there has to be defined a method called 'GET'.
* Method called 'GET' has to return a function that would expect a callback as its first argument. This function will make an actual HTTP request and on ready state it will call this callback.

**Comment by lukehoban** [comment]
That's exactly right.  This example is indeed more complex than most of the others in the doc - it may be worth adding some simpler ones instead - but I find this one a nice holistic example of the kind of thing that's possible at the more extreme end of using this feature.

**Comment by computersarecool** [comment]
I am sorry but @mieszko4 or @lukehoban  could you actually pencil that one out, here if possible?

**Comment by mieszko4** [comment]
@computersarecool You can define `POST` tag function like this:

```javascript
//define POST tag function
let POST = function (strings, ...values) {
  //connect all strings with values
  let parts = strings.map(function (string, i) {
    if (typeof values[i] !== 'undefined') {
      return string + values[i];
    } else {
      return string;
    }
  });
  
  //parse url, headers, and body
  let request = parts.join('');
  let [ header, body ] = request.split(/\n\s*\n/);
  
  let [ url, ...headers ] = header.split('\n');
  
  //add an extra header
  headers.push('From: es6@example.com');
  
  //trim whitespaces and parse name and value for each header
  url = url.trim();
  body = body.trim();
  headers = headers.map(function (header) {
    let [ name, value ] = header.split(':');
    name = name.trim();
    value = value.trim();
    
    return {
      name,
      value
    };
  });
  
  //return request function
  return function (onReadyStateChangeHandler) {
    const ASYNCHRONOUS = true;
    
    let xhttp = new XMLHttpRequest();
    
    xhttp.open(
      'POST',
      url,
      ASYNCHRONOUS
    );
    
    headers.forEach(function (header) {
      xhttp.setRequestHeader(header.name, header.value);
    });
    
    xhttp.onreadystatechange = onReadyStateChangeHandler;
    
    xhttp.send(body);
  };
};
```
And then use it like this:

```javascript
//define interpolation variables and ready function
let a = 1;
let b = 2;
let credentials = 'password';
let foo = 'a';
let bar = 'b';
let myOnReadyStateChangeHandler = function (event) {
  let xhttp = event.target;
  
  if (xhttp.readyState == 4) {
    console.log('Request completed with: ', xhttp.status, xhttp.responseText);
  }
};

// Construct an HTTP request. Prefix is used to interpret the replacements and construction
POST`http://foo.org/bar?a=${a}&b=${b}
  Content-Type: application/json
  X-Credentials: ${credentials}
  
  { "foo": ${foo},
  "bar": ${bar}}`
(myOnReadyStateChangeHandler);
```

This works in Firefox 41.0.1. I know that @lukehoban used GET in his example but since he put request body he most likely meant POST as with GET you cannot send request body

**Comment by computersarecool** [comment]
Wow. Pretty complex stuff - Thank you for the example!

**Comment by berniegp** [comment]
I still couldn't grasp it after this issue so here's another source I found: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates

> A more advanced form of template literals are tagged templates. Tags allow you to parse template literals with a function. The first argument of a tag function contains an array of string values. The remaining arguments are related to the expressions. In the end, your function can return your manipulated string (or it can return something completely different as described in the next example). The name of the function used for the tag can be whatever you want.
