### ISSUE TITLE
I expected nums to be [1,2,3]

### ISSUE THREAD

**Issue by lucidtech** [lukehoban/es6features#64]
var nums = evens.map((v, i) => v + i);
nums returns [0,3,6..]
why not v-i that returns [1,2,3]

... confused

**Comment by lukehoban** [comment]
Not sure what issue you are pointing out here.   

The `map` function takes a callback and invokes it with the value (`v`) and index (`i`) of each element.

So this example:

```javascript
let evens = [0,2,4]
let nums = evens.map((v,i) => v + i)
console.log(nums)
```

Will print `[0,3,6]`.  

See example on [babeljs](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=let%20evens%20%3D%20%5B0%2C2%2C4%5D%0Alet%20nums%20%3D%20evens.map((v%2Ci)%20%3D%3E%20v%20%2B%20i)%0Aconsole.log(nums)%0A%0A).
