### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by balupton** [lukehoban/es6features#70]
It would be awesome to be able to see performance comparisons between ES6 features and the ES5 way of doing the same or similar thing.

For instance, with fat arrows, I've love to see the performance comparison between:

- `(function(){})()`
- `(function(){}).bind(this)()`
- `(=>)()`

**Comment by balupton** [comment]
I've created https://github.com/bevry/es6-benchmarks to test these things. Perhaps we could link to each other?

**Comment by getify** [comment]
I think it's impossible to give an accurate answer of these things... all ES6 features are landing new in browsers, not having had any chance yet for the browser makers to optimize them. A performance comparison 3-4 years from now would make sense, but at the moment I think any results you see are totally bogus and misleading -- that is, tomorrow what you see today as slow might be really fast once they optimize it.

**Comment by balupton** [comment]
> that is, tomorrow what you see today as slow might be really fast once they optimize it.

But that's always the case... And the opposite can equally be the case, that they don't become faster significantly.

The comparison is useful because it is for today, not for tomorrow, because we live in the today, we don't live in the tomorrow. If I'm writing software today, I want to know what is faster today.

**Comment by mathiasbynens** [comment]
@balupton I think your suggestion is outside the scope of this repository, of which the only aim is to demonstrate the new functionality.

**Comment by getify** [comment]
> If I'm writing software today, I want to know what is faster today.

Not me. How it runs today is far less important than how it will run starting tomorrow and from then on.

**Comment by KenPowers** [comment]
I have an idea related to this discussion but it wouldn't necessarily be a good fit for either repo.

What about an automated test suite which consistently publishes results on new browser releases (as well as beta releases)? Power it with something like BrowserStack and make the test suite open source so anybody can contribute. New results would be published whenever a pull request is merged or a browser update is released.

**Comment by getify** [comment]
@KenPowers that might perhaps be more appropriate for: https://github.com/tc39/test262

**Comment by lukehoban** [comment]
I agree with @getify that this repo is probably not the right place for this kind of performance data.  

I do think this is something that would be interesting to do somewhere, as having this data visible can help push implementation progress, as kangax's compatibility chart, and benchmarks like SunSpider did in the past.

**Comment by balupton** [comment]
No worries. I'll continue making https://github.com/bevry/es6-benchmarks better.
