### ISSUE TITLE
React + Flux Store Example in ES6

### ISSUE THREAD

**Issue by urbanvikingr** [lukehoban/es6features#80]
How would you write this in ES6?

var EventEmitter = require("events").EventEmitter
var assign = require("react/lib/Object.assign")
...
var ProductStore = assign({}, EventEmitter.prototype, {
...
  emitChange: function() {
    this.emit("change")
  },

**Comment by domenic** [comment]
Perhaps this is a question better for StackOverflow, instead of filed as a bug on the ES6 feature showcase?

**Comment by urbanvikingr** [comment]
Perhaps it could be added to the already excellent list of examples :)

**Comment by domenic** [comment]
IMO framework-specific examples are not a great fit. But that's the last I'll say on the matter.

**Comment by jiyinyiyong** [comment]
Probably an issue related to Babel https://gitter.im/babel/babel
