### ISSUE TITLE
Maybe a typo

### ISSUE THREAD

**Issue by rocky-jaiswal** [lukehoban/es6features#83]
Maybe you have a typo in Modules (in Readme) in mathplusplus

export * from "lib/math";
should be
import * from "lib/math";

or maybe I am wrong :)

**Comment by getify** [comment]
Nope, it's correct. There's a `export *` form that "re-exports" a module.

**Comment by rocky-jaiswal** [comment]
Sorry for wasting your time. Thanks :)
