### ISSUE TITLE
Current browser support

### ISSUE THREAD

**Issue by xPetrus** [lukehoban/es6features#84]
Add a section with current browser ES6 feature support?

**Comment by lukehoban** [comment]
This is better handled elsewhere I think.  There is already a link to kangax's ES6 compat table in the first paragraph, which is the best summary I know of right now.

**Comment by hjzheng** [comment]
@xPetrus  you can use this link http://ruanyf.github.io/es-checker/ to check current browser ES6 feature support.

**Comment by xPetrus** [comment]
Thanks! I've already been studying it :)
