### ISSUE TITLE
`Proxy` is not a `Function` now

### ISSUE THREAD

**Issue by benjycui** [lukehoban/es6features#93]
I test `new Proxy` in io.js(v3.1.0), an error was threw: "Proxy is not a function". And I found that we should create Proxy with `Proxy.create` now. So, maybe you should update [this](https://github.com/lukehoban/es6features#proxies).

**Comment by getify** [comment]
Nothing has changed about the ES6 spec... `Proxy(..)` is [definitely a constructor](http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-target-handler) and must be called as such.

I don't know where `Proxy.create(..)` is coming from, but I don't think it's in the spec.

**Comment by lukehoban** [comment]
V8 does not implement ES6 Proxies correctly yet - see [kangax's compatiiblity table](http://kangax.github.io/compat-table/es6/#Proxy).  The API you are seeing in io.js is, I believe, a fairly old iteration of the ES6 draft standard.
